doctrine:
  dbal:
    default_connection: dev
    connections:
      dev:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_general_ci
        host: '%env(DB_DEV_HOST)%'
        port: '%env(DB_DEV_PORT)%'
        dbname: '%env(DB_DEV_DATABASE)%'
        user: '%env(DB_DEV_USERNAME)%'
        password: '%env(DB_DEV_PASSWORD)%'

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Domain/Entity'
        prefix: 'App\Domain\Entity'
        alias: App
    metadata_cache_driver: apc
    result_cache_driver: apc
    query_cache_driver: apc